# Exported from Render on 2024-03-27T09:18:06Z
services:
- type: web
  name: bot
  runtime: python
  repo: https://github.com/alptangal/bot
  branch: render
  plan: free
  envVars:
  - key: botToken1
    sync: false
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: python main.py
version: "1"
